"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UI_REPOSITION_SIDENOTES = exports.UI_UPDATE_COMMENT = exports.UI_SELECT_ANCHOR = exports.UI_DESELECT_SIDENOTE = exports.UI_SELECT_SIDENOTE = exports.UI_DISCONNECT_ANCHOR = exports.UI_CONNECT_ANCHOR_BASE = exports.UI_CONNECT_ANCHOR = exports.UI_DISCONNECT_SIDENOTE = exports.UI_CONNECT_SIDENOTE = exports.ANCHOR_BASE = void 0;
exports.ANCHOR_BASE = 'ANCHOR_BASE';
exports.UI_CONNECT_SIDENOTE = 'UI_CONNECT_SIDENOTE';
exports.UI_DISCONNECT_SIDENOTE = 'UI_DISCONNECT_SIDENOTE';
exports.UI_CONNECT_ANCHOR = 'UI_CONNECT_ANCHOR';
exports.UI_CONNECT_ANCHOR_BASE = 'UI_CONNECT_ANCHOR_BASE';
exports.UI_DISCONNECT_ANCHOR = 'UI_DISCONNECT_ANCHOR';
exports.UI_SELECT_SIDENOTE = 'UI_SELECT_SIDENOTE';
exports.UI_DESELECT_SIDENOTE = 'UI_DESELECT_SIDENOTE';
exports.UI_SELECT_ANCHOR = 'UI_SELECT_ANCHOR';
exports.UI_UPDATE_COMMENT = 'UI_UPDATE_COMMENT';
exports.UI_REPOSITION_SIDENOTES = 'UI_REPOSITION_SIDENOTES';
//# sourceMappingURL=types.js.map